### ISSUE TITLE
use emit stage for compatibility with html-webpack-plugin

### ISSUE THREAD

**Issue by neben** [mikechau/sri-stats-webpack-plugin#1]
I'm using `html-webpack-plugin` to add the integrity field to the script tag in the HTML. However, I had to change your `after-emit` handler to run in `emit` stage, because html-webpack-plugin runs at `emit`, too. Is there something I'm missing here? Or should there be an option for choosing at which stage to run?

**Comment by mikechau** [comment]
Ah that makes sense, if you want to make a PR with that change - I'll gladly merge it in. :+1:

**Comment by neben** [comment]
here you go #2

**Comment by mikechau** [comment]
Thanks again!
